version: '3'

services:
  database:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: didakeys
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - didakeys_db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  didakeys_db_data:
